### ISSUE TITLE
report doesn't show @Before and @After times

### ISSUE THREAD

**Issue by avishayh** [fabriciorby/maven-surefire-junit5-tree-reporter#20]
All @Before an @After annotations are not displayed as part of the report

in the original report you can see the time elapsed for the entire class, but in the tree report you just see the elapsed time per method. 

e,g:
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, **Time elapsed: 0.034 s** - in org.example.MyTest 

if for example, you have a @Before method in your class which takes few seconds, you will not be able to capture that

**Comment by fabriciorby** [comment]
In order to fix Nested Tests outputs I've raised this Jira Ticket for Surefire: https://issues.apache.org/jira/browse/SUREFIRE-2111

Just documenting here.
