### ISSUE TITLE
[Not An Issue] Just want to see I like this extension.

### ISSUE THREAD

**Issue by TimeInvestor** [fabriciorby/maven-surefire-junit5-tree-reporter#24]
Thanks for sharing.
It's awesome!
I've been looking for such a solution for a long time.

**Comment by fabriciorby** [comment]
Hey @TimeInvestor,

Thank you very much! :)

If you want to know a bit more about the motivation you can read this small article here: https://medium.com/wearewaes/my-journey-to-a-clear-test-output-in-maven-df82fe272249

**Comment by TimeInvestor** [comment]
Thanks for sharing.

BTW, not sure if it is related to this extension, but my tests encounter such issue

![image](https://user-images.githubusercontent.com/4818798/185085922-f262836e-9400-4271-bcfb-c1a1377cfd09.png)

If just re-run it, it will run fine.

**Comment by fabriciorby** [comment]
Maybe it is, can you provide a way for me to recreate this error?

**Comment by TimeInvestor** [comment]
> Maybe it is, can you provide a way for me to recreate this error?

Sorry for late reply.
I tried to set up a simple repo (without any credential info) to reproduce the issue.
However, I could not reproduce the issue anymore.
Close this issue for now.
Will let you know again if I encounter the issue in the future.
