### ISSUE TITLE
(Some) nested tests are not printed at all

### ISSUE THREAD

**Issue by rkraneis** [fabriciorby/maven-surefire-junit5-tree-reporter#26]
Reproducer: https://github.com/rkraneis/tree-reporter

Context: https://github.com/rkraneis/tree-reporter/blob/2a656ebb9e4c5c39371b5fd4e849c326641437fb/README.md

Actual:

```
├─ io.github.rkraneis.treereporter.OuterTest - 0.036s
│  └─ ✔ test - 0.011s
├─ ── InnerSub2 - 0.001s
│     ├─ ✔ testFromBase - 0s
│     └─ ✔ testInnerSub2 - 0.001s
```

Expected:

```
├─ io.github.rkraneis.treereporter.OuterTest - 0.036s
│  └─ ✔ test - 0.011s
├─ ── Inner1 - 0.001s
│     └─ ✔ testInner1 - 0.001s
├─ ── Inner2 - 0.001s
│     └─ ✔ testInner2 - 0.001s
├─ ── InnerSub1 - 0.001s
│     ├─ ✔ testFromBase - 0s
│     └─ ✔ testInnerSub1 - 0.001s
├─ ── InnerSub2 - 0.001s
│     ├─ ✔ testFromBase - 0s
│     └─ ✔ testInnerSub2 - 0.001s
```

The tests themselves are executed (`Tests run: 7, Failures: 0, Errors: 0, Skipped: 0`).

N.B.: I started my own [tree view printer](https://github.com/rkraneis/junit-platform-console-testexecutionlisteners) a while ago (basically just as a copy of what the junit jupiter console launcher does), but didn't like the messy setup (test execution listener). Your POM based version would be much better, setup-wise.

**Comment by fabriciorby** [comment]
Yeah, there's a bug when there is more than one `@Nested` class in the same Test file, interesting how I did not test this scenario before!

Not so easy but I'll be looking for a fix ASAP! Thanks!
