### ISSUE TITLE
Newer Surefire – elapsed time output format wrong

### ISSUE THREAD

**Issue by hho** [fabriciorby/maven-surefire-junit5-tree-reporter#50]
[Since Surefire 3.1.1](https://github.com/apache/maven-surefire/commit/ed307a68224bb4cb1ea52c4e4ceaa652170c7472#diff-efbf1a613b0d3b854d7a732ab8f6221fa5ac34210449cdfb4eee6bb61a60c1ccR60) the formatting of the elapsed time comes already with the `s` appended.

However, the TreePrinter [appends another `s`](https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/blob/45484196182a1de41cbb5da699a24d7086d8da3a/src/main/java/org/apache/maven/plugin/surefire/report/TreePrinter.java#L232), leading to output like this:

```
…
[INFO] │  ├─ ✔ validDataUrlIsParsed(String)[1] image/png - 0.006 ss
[INFO] │  ├─ ✔ validDataUrlIsParsed(String)[2] image/jpeg - 0.001 ss
[INFO] │  ├─ ✔ validDataUrlIsParsed(String)[3] image/jpg - 0.001 ss
…
```

**Comment by michael-o** [comment]
Doppelt hält besser!
